// =====================================================
// RUSYA - HİÇBİR ÜRÜNDE BULUNMAMASI GEREKEN PESTİSİTLER
// =====================================================
export const RUSSIA_ZERO_TOLERANCE_LIST = [
  "0-ethyl-0-phenyl-S-propylthiophosphate",
  "0,0-Dimethyl-0-(4-methylthio-3-methyl-phenyl)thiophosphate",
  "1,1-dioxothiolanine-3-dithiocarbamic acid triethylene salt",
  "1-(2-chloroethoxycarbonylmethyl)-naphthalenesulfonic acid calcium salt",
  "[1-(4-nitrophenyl)-2-amino-1,3-propanediol] nitrate salt",
  "2,4-DV (4-(2,4-dichlorophenoxy)butanoic acid)",
  "2-amino-6-dimethylamino-4-chloro-1,3,5-triazine",
  "2-carbomethoxy-aminoquinazolone",
  "2-methyl-4-dimethylaminomethyl-benzimidazol-5-ol dihydrochloride",
  "2-methyl-4-oxo-3-(prop-2-enyl)-2-cyclopenten-2-en-1-yl... cyclopropane carbonate",
  "2-chloroethylphosphonic acid benzimidazole salt",
  "2-(diphenylacetyl)1H-inden-1,3-2H-dione",
  "2-[4-(1-methylethyl)phenyl phenylacetyl]-1H-indan-1,3 dione",
  "2-[(4-chlorophenyl)phenylacetyl]-1H-inden-1,3(2H)-dione",
  "3,3-dichloro-tri-cyclo-(2,2,1)-hepta-5-en-2-spiro-[2'-(4',5-dichloro-4'-cyclopentene-1',3'-dione]",
  "6-methyl-2-thiouracil sodium salt",
  "N-hexyloxymethylazepine",
  "N,N-β-hydroxyethyl morpholinium chloride",
  "N-β-ethoxyethyl chloroacetamide",
  "N-(isopropoxycarbonyl-0-(4-chlorophenylcarbamoyl)-ethanolamine",
  "N-(4-chlorophenyl)-4,6-dimethyl-3-carboxypyridin-2-one",
  "N-methyl-0-tolylcarbamate",
  "S-methyl-N-(methyl-carbomoyl)oxythioacetimidate",
  "Alkyl ether sulfate sodium salt",
  "Acetoxime (N-propane-2-ylidenehydroxylamine)",
  "Benzoylformic acid sodium salt",
  "Benzoylpropethyl",
  "Bensulide",
  "Binapacryl",
  "Bicyclopyrone",
  "Methylbenzaldehyde 4-triphenylphosphonium bromide (karışım)",
  "Bronopol (2-bromo-2-nitropropane-1,3-diol)",
  "Dibromochloropropane (1,2-dibromo-3-chloropropane)",
  "Diisopropyldi-thiophosphonic acid potassium salt",
  "Degadroaspartic acid dimethyl ester potassium salt",
  "Dichloral urea",
  "Dihorpropene + dichloropropane",
  "Dicyandiamide",
  "Isobutene dichlorides (mixture)",
  "Isofenphos",
  "Iprobenfos",
  "Polyoxin complex",
  "Inhibited petroleum oil",
  "Metammethyldithiocarbamic acid",
  "Rapeseed oil methyl ester (Mero's adjuvant)",
  "Sodium salicylate",
  "Naphtalen-1-ylthiocarbamide",
  "Neonol (2-[2-(4-nonoylphenoxy)ethoxy]ethanol)",
  "Nitroalkylphenolates",
  "Nonylphenol (2-nonylphenol)",
  "Hydroxymethyl ethyl ketone",
  "Oleic alcohol (HD-OSENOL)",
  "Paclobutrazol",
  "Pinolene",
  "Polyoxyethylene dodecyl ether",
  "Nonionic surfactant karışımı (Amigo, Amigo Star)",
  "Nonionic surfactant karışımı (DASH)",
  "Nonionic surfactant karışımı (Corvette)",
  "Sulprofos",
  "Sulfometuron-methyl",
  "Sulfometuron-methyl potassium salt",
  "Tetramethryl-methylenediamine oxalate",
  "Fenpiclonil",
  "Fluroxypyr-meptyl",
  "Quinomethionate",
  "Cynidone-ethyl",
  "2,3,5-trichloropyridine; 2-ethoxyester-2-chloropropinoic acid; 4-(3',5'-dichloro-pyridyl-2-oxy)phenol"
];

// =====================================================
// RUSYA - LİMİT BELİRLENMESİNE GEREK YOK MADDELERİ
// =====================================================
export const RUSSIA_NO_LIMIT_LIST = [
  // Bitki büyüme düzenleyiciler
  "Indole-3-acetic acid (indolyl-3-acetic acid)",
  
  // 2,4-D türevleri
  "2,4-D butyl ether",
  "2,4-D düşük volatil (uçucu) ester'ler",
  "2,4-D 2-ethylhexyl ether",
  "2,4-D octyl ether",
  
  // Bacillus thuringiensis (Bt) türleri
  "Bacillus thuringiensis var. dendrolimus",
  "Bacillus thuringiensis var. insektus",
  "Bacillus thuringiensis var. kurstaki",
  "Bacillus thuringiensis var. tenebrionis",
  "Bacillus thuringiensis var. thuringiensis (spore-crystalline complex)",
  "Bacillus thuringiensis var. thuringiensis (spore-crystalline complex and exotoxin)",
  
  // Biyolojik ajanlar
  "Beauveria bassiana (conidia)",
  "Pseudomonas syringae (bacteriophage)",
  "Verticillium lecanii (conidin)",
  "Anaerobik bakteri aktif kültür",
  
  // Herbisi türevleri
  "MCPA 2-ethylhexyl ether",
  "Clopyralid 2-ethylhexyl ether",
  
  // Kimyasal maddeler
  "Acrolein (prop-2-enal)",
  "Acetylenic alcohol (prop-2-yn-1-ol)",
  "Carbon disulfide / methane disulfide",
  
  // Doğal maddeler
  "Serbest aminoasitler",
  "Arachidonic acid",
  "Polyprenols acetates (Sibirya köknar iğnelerinden)",
  "Benzoic acid (tüm gıda ürünleri)",
  "Humic acids",
  "Humic acids ammonium salts",
  "Humic acids sodium salts",
  "Natural terpenoids (mixture)",
  
  // Rodentisitler
  "Brodifacoum",
  "Bromadiolone",
  "Isopropylphenacin",
  "Triphenacin (by difenacin)",
  "Ethylphenacil",
  
  // Virusler (biyolojik)
  "Granulosa virus (winter cutworm polyhedrosis)",
  "Codling moth granulosa virus",
  "Bollworm nuclear polyhedrosis virus",
  "Ringed silkworm nuclear polyhedrosis virus",
  "Gypsy moth nuclear polyhedrosis virus",
  
  // Bitki büyüme düzenleyiciler
  "Gibberellic acids sodium salts",
  "Gibberellin-A3",
  
  // Yardımcı maddeler
  "MSLO I-8A industrial (vaseline)",
  "Polyether-modified trisiloxane (surfactant Super Cap)",
  "Tris(2-ethylhexyl) phosphate (adjuvant)",
  "Ester phosphate (adjuvant)",
  "Aliphatic alcohol ethoxylate C8-C10",
  "Isodecyl alcohol ethoxylate (adjuvant)",
  "Sorbitan monolaurate ethoxylate (NN-21 bioactivator)",
  
  // Diğer
  "(chloride-N,N-dimethyl-N-)-(2-chloroethyl) hydrosynium",
  "Amino fumaric acid dimethyl ether",
  "Poly-beta-hydrobutyric acid",
  "Polyoxin B — cucumber, grape",
  "Metabolic products of ginseng endophyte fungi",
  "Metabolic products of sea buckthorn endophyte fungi",
  "Sulfur (kükürt)",
  "Silicon dioxide (amorphous) — grain, legumes, oily seeds"
];

// =====================================================
// TÜRKİYE - YASAKLI PESTİSİTLER
// =====================================================
export const TURKEY_BANNED_LIST = [
  "1,2-dibromoethane (ethylenedibromide)",
  "1,3-dichloropropene",
  "1,1-dichloro-2,2-bis (4-ethylphenyl) ethane",
  "2,4,5-T",
  "4-CPA (4-Chlorophenoxy Acetic Acide)",
  "Acephate",
  "Acetochlor",
  "Alachlor",
  "Aldicarb",
  "Aldrin ve Dieldrin",
  "Aminotriazole",
  "Amitraz",
  "Anilofos",
  "Atrazine",
  "Azinphos-ethyl",
  "Azinphos-methyl",
  "Azocyclotin ve Cyhexatin",
  "Benfuracarb",
  "Bioallethrin (Esbiothrin)",
  "Bitertanol",
  "Bifenthrin",
  "Bromacil",
  "Bromophos-ethyl",
  "Bromopropylate",
  "Bronopol",
  "Butralin",
  "Cadusafos",
  "Camphechlor (Toxaphene)",
  "Carbaryl",
  "Carbendazim ve benomyl",
  "Carbofuran",
  "Carbosulfan",
  "Chinomethionat",
  "Chlordane",
  "Chlorfenapyr",
  "Chlorfenvinphos",
  "Chlorfluazuron",
  "Chlorobenzilate",
  "Chloroneb",
  "Chloropicrin",
  "Chloropropylate",
  "Chlorothalonil",
  "Chorpyrifos",
  "Chorpyrifos methyl",
  "Clothianidin",
  "Civa Bileşikleri",
  "Coumachlor",
  "Cyanazine",
  "Cyfluthrin",
  "Hydrogen cyanide",
  "Cycloate",
  "Cyclosulphamuron",
  "Cyanamide",
  "DDT",
  "Diafenthiuron",
  "Diazinon",
  "Dichlofluanid",
  "Dichlorvos (DDVP)",
  "Dicofol",
  "Difenacoum",
  "Difenzoquat",
  "Dimethipin",
  "Diniconazole",
  "Dinocap",
  "Dioxacarb",
  "Dioxathion",
  "Diphenamid-p",
  "DNOC",
  "Endosulfan",
  "Endothal",
  "Endrin",
  "EPTC",
  "EPN",
  "Ethalfluralin",
  "Ethiofencarb",
  "Ethion",
  "Ethirimol",
  "Ethoate-methyl",
  "Ethoxysulfuron",
  "Fenamidone",
  "Fenarimol",
  "Fenbutatin oxide",
  "Fenitrothion",
  "Fenpiclonil",
  "Fenpropathrin",
  "Fenpropimorph",
  "Fentinacetate",
  "Fentinhydroxide",
  "Fenthion",
  "Fipronil",
  "Flamprop-m-isopropyl",
  "Flocoumafen",
  "Flubenzimine",
  "Flucythrinate",
  "Flufenoxuron",
  "Flumetsulam",
  "Fluorodiphenyl",
  "Fluridone",
  "Flusilazole",
  "Fluthiacet-methyl",
  "Fomesafen",
  "Formothion",
  "Furathiocarb",
  "Halfenprox",
  "Heptachlor",
  "Hexachlorobenzene (HCB)",
  "Hexachlorociclohexane (HCH), alpha-isomer",
  "Hexachlorociclohexane (HCH), beta-isomer",
  "Hexaconazole",
  "Hexaflumuron",
  "Hydrogen peroxide",
  "Imazamethabenz-methyl",
  "Imazapic",
  "Imazapyr",
  "Imazethapyr",
  "Ioxynil",
  "Iprodione",
  "Isofenphos",
  "Kinetin (cis-zeatin)",
  "Leptophos",
  "Lindane",
  "Maneb",
  "Mephosfolan",
  "Methabenzthiazuron",
  "Methamidophos",
  "Methidathion",
  "Methiocarb",
  "Methomyl",
  "Methoprene",
  "Methyl bromid",
  "Methominostrobin",
  "Metosulam",
  "Mevinphos",
  "Molinate",
  "Monocrotophos",
  "Monolinuron",
  "Norflurazon",
  "Novaluron",
  "Nuarimol",
  "Ofurace",
  "Omethoate",
  "Orthosulfamuron",
  "Oxadixyl",
  "Oxamyl",
  "Oxycarboxin",
  "Oxydemeton-methyl",
  "Paraquat",
  "Parathion",
  "Parathion-methyl",
  "Permethrin",
  "Phenthoate",
  "Phorate",
  "Phosalone",
  "Phoshamidon",
  "Pinolene",
  "Primisulfuron",
  "Procymidone",
  "Profenophos",
  "Prometryn",
  "Propanil",
  "Propargite",
  "Propiconazole",
  "Propineb",
  "Propoxur",
  "Prothiofos",
  "Prothoate",
  "Pymetrozine",
  "Pyrazophos",
  "Pyridaphenthion",
  "Pyrimidifen",
  "Pyrithiobac Sodium",
  "Quinalphos",
  "Quinoxyfen",
  "Quintozene (PCNB)",
  "Resmethrin",
  "Sethoxydim",
  "Simazine",
  "TCMTB",
  "Tebuthiuron",
  "Tepraloxydim",
  "Terbutryn",
  "Tetradifon",
  "Thiacloprid",
  "Thiazafluron",
  "Thiazopyr",
  "Thidiazuron",
  "Thiocyclam",
  "Thiometon",
  "Thiobencarb",
  "Thiodicarb",
  "Tolylfluanid",
  "Tolfenpyrad",
  "Tralkoxydim",
  "Tralomethrin",
  "Triadimenol",
  "Triasulfuron",
  "Triazamate",
  "Triazophos",
  "Trichlorfon",
  "Tridemorph",
  "Trifloxysulfuron",
  "Trifluralin",
  "Triforine",
  "Vinclozolin",
  "Zineb"
];

// =====================================================
// TÜM LİSTELER TEK BİR OBJEDE
// =====================================================
export const CUSTOM_LISTS = {
  TURKEY_BANNED: TURKEY_BANNED_LIST,
  RUSSIA_ZERO_TOLERANCE: RUSSIA_ZERO_TOLERANCE_LIST,
  RUSSIA_NO_LIMIT: RUSSIA_NO_LIMIT_LIST,
  RUSSIA_BANNED: [],  // Varsa ekle
};